name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dwitabputri/mjs-tes:latest

      - name: Deploy to Laptop Y
        run: |
          ssh user@192.168.1.11 'docker stop my-container'
          ssh user@192.168.1.11 'docker rm my-container'
          ssh user@192.168.1.11 'docker pull dwitabputri/mjs-tes:latest'
          ssh user@192.168.1.11 'docker run -d --name my-container dwitabputri/mjs-tes:latest'
